Initial parser log proto
Ingenio/keen-teamcity-logs-parser pull request #2
Opened 2016-12-22 08:53 UTC by AlexanderKapelyukhovskiy

2016-12-23 01:03 UTC, Restuta commented on lib/index.js
> +let head = new LogEntry('00:00:00', 'HEAD of the Log', 0) //TODO: parse date from Log
easy with momentjs or vanilla `new Date()`

2016-12-23 01:23 UTC, Restuta requested changes

2016-12-23 01:23 UTC, Restuta commented on lib/log-entry.js
> +  this.parent = parent
apparently "parent" is a reserved variable on the client, while it's a server-side code I'd recommend to use `parentNode`

2016-12-23 01:23 UTC, Restuta commented on lib/log-parser.js
> +const parseLogDate = (logDateString, startDate) => {
why this can't be done with moment?

2016-12-23 01:23 UTC, Restuta commented on lib/log-parser.js
> +  const result = logLine.match(logEntryPattern)
name of the variable is meaningless, result of what? It's actually an array of matches, so `logEntryMatches` is far better name

2016-12-23 01:23 UTC, Restuta commented on lib/log-parser.js
> +const logEntryPattern = /^\[(\d{2}:\d{2}:\d{2})\][ |\w]:(\t*)(.*)$/
Triple checked that it maches all log entries?

2016-12-23 01:23 UTC, Restuta commented on lib/log-parser.js
> +const parser = (filePath, callBack) => {
collbacks are so 2000, use promises or generators or even async/await, also `callback` is always all lowercase or just `cb` in node world

2016-12-23 01:23 UTC, Restuta commented on lib/log-parser.js
> +      level = tabs.length
Have you double checked that it's tabs and not spaces?

2016-12-23 01:23 UTC, Restuta commented on lib/index.js
> +parser(
this is confusing name, a function should be a verb, it should be either `logParser.parse` or just `parseLog`

2016-12-23 01:41 UTC, Restuta commented
Those comments is one thing, but I have a bigger concern with the current approach, since most interesting part is to assign to each node a numerical value, time it took in seconds to execute this line. TeamCity puts into log times sometimes, I am not sure how reliable is that and if we can trust it.

If we _can't_ trust it, then I think we can calculate time it took in the following way:

Let's say we are reading following log:

```
[1m10s] Entry A
  [1m12s] Entry B
  [1m15s] Entry C
```

correct tree would look like:
```
     A(2+3=5s)
  /      \
B(2s)  C(3s)
```

But in order to calculate that we need to do two things: 
1. read lines in pairs and subtract Entry B time from Entry A time
2. after tree is built we should have all leaf values set, so we should need to traverse the tree in a special way updating leaf parents to the sum of the leafs. *This is based under assumption that time it took to execute a parent = sum of all children times*, which may not be true. If it's not true, then we have option 3.
3. More reliable way to calculate times could be to just have a sorted tree, where on each level tree is sorted in the order log is sorted (by time), so then after tree is built we can do breadth-first traversal and calculate time it took by just doing node (C - B), *This is based under assumption that time it took to execute a parent NOT NECESSARILY equals to sum of all children times, in this case we can even add a "pseudo-node" with the delta if it's non 0, so on the flame-chart we can see time not reported by teamcity (spent on something else), I'd assume it's pretty minimal and maybe we can ignore that for now.

2016-12-23 17:13 UTC, AlexanderKapelyukhovskiy commented on lib/log-parser.js
> +const logEntryPattern = /^\[(\d{2}:\d{2}:\d{2})\][ |\w]:(\t*)(.*)$/
@Restuta, could you please clarify this note?

2016-12-23 17:18 UTC, AlexanderKapelyukhovskiy commented on lib/log-parser.js
> +const parseLogDate = (logDateString, startDate) => {
We probably can simplify this part of parsing. Right now we have only time inside log entries like 
```
[02:30:07] : Finalize build settings
```

and we also have full start date in second line of log:
```
Started 'Thu Dec 15 02:37:22 PST 2016' on 'SAC-CORP-TC2' by 'Schedule Trigger
```

so we need to get time from second log line and using time from log entry create full log date for each log entry

2016-12-23 17:23 UTC, AlexanderKapelyukhovskiy commented on lib/log-parser.js
> +      level = tabs.length
yes
![Alt](http://image.prntscr.com/image/725c04d66bd44ce8a49cbd5f32c5109b.png "sample")

2016-12-23 22:15 UTC, Restuta approved these changes

2016-12-23 22:16 UTC, Restuta commented
What do you think about my comment?

2016-12-26 20:37 UTC, Restuta requested changes

2016-12-26 20:37 UTC, Restuta commented on index.html
> +    <script type="text/javascript" src="http://d3js.org/d3.v3.min.js"></script>
That's an old version of D3, we need to use v4

2016-12-27 09:30 UTC, AlexanderKapelyukhovskiy commented on index.html
> +    <script type="text/javascript" src="http://d3js.org/d3.v3.min.js"></script>
I was not able to find flame graph library integrated with d3 v4. 
As you can see from https://github.com/spiermar/d3-flame-graph/blob/master/package.json
it depends on "d3": "^3.5.6"

2016-12-27 23:24 UTC, Restuta approved these changes

2016-12-30 07:30 UTC, Restuta commented on lib/visualizable-log-tree-builder.js
> +const mmss = secs => {
wins a :1st_place_medal:  for easy to understand name

2016-12-30 07:31 UTC, Restuta commented on lib/visualizable-log-tree-builder.js
> +  if(secs <= 0)
always use `{`, need to ESLint this

2017-01-04 08:48 UTC, merged